### ISSUE TITLE
0 source stem points are extracted

### ISSUE THREAD

**Issue by coding-encoding** [zexinyang/GlobalMatch#4]
![image](https://github.com/user-attachments/assets/6de57c1c-ee7d-4757-9cf0-4da2eb8ada24)
Hello, thanks for sharing your code. The results show that there is no stem detected, I am wondering why this would happen.

**Comment by zexinyang** [comment]
Hi, thank you for your interest in our work!
Are you running the original code on the Tongji-Trees dataset? It’s hard to pinpoint the issue without more details about your data. Could you share your point clouds or at least some visualizations?

**Comment by zexinyang** [comment]
Closed for now. Please feel free to reopen if there are any updates.
